name = "x-evm-rpc-server"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false

[[routes]]
pattern = "x-evm-rpc.algorand.tech"
custom_domain = true
